package com.example.KMA.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.full_name
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	private String full_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_name
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	private String user_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_password
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	private String user_password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.role
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	private String role;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.full_name
	 * @return  the value of user.full_name
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public String getFull_name() {
		return full_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.full_name
	 * @param full_name  the value for user.full_name
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public void setFull_name(String full_name) {
		this.full_name = full_name == null ? null : full_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_name
	 * @return  the value of user.user_name
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public String getUser_name() {
		return user_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_name
	 * @param user_name  the value for user.user_name
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public void setUser_name(String user_name) {
		this.user_name = user_name == null ? null : user_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_password
	 * @return  the value of user.user_password
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public String getUser_password() {
		return user_password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_password
	 * @param user_password  the value for user.user_password
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public void setUser_password(String user_password) {
		this.user_password = user_password == null ? null : user_password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.role
	 * @return  the value of user.role
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.role
	 * @param role  the value for user.role
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public void setRole(String role) {
		this.role = role == null ? null : role.trim();
	}
}