package com.example.KMA.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public UserExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andFull_nameIsNull() {
			addCriterion("full_name is null");
			return (Criteria) this;
		}

		public Criteria andFull_nameIsNotNull() {
			addCriterion("full_name is not null");
			return (Criteria) this;
		}

		public Criteria andFull_nameEqualTo(String value) {
			addCriterion("full_name =", value, "full_name");
			return (Criteria) this;
		}

		public Criteria andFull_nameNotEqualTo(String value) {
			addCriterion("full_name <>", value, "full_name");
			return (Criteria) this;
		}

		public Criteria andFull_nameGreaterThan(String value) {
			addCriterion("full_name >", value, "full_name");
			return (Criteria) this;
		}

		public Criteria andFull_nameGreaterThanOrEqualTo(String value) {
			addCriterion("full_name >=", value, "full_name");
			return (Criteria) this;
		}

		public Criteria andFull_nameLessThan(String value) {
			addCriterion("full_name <", value, "full_name");
			return (Criteria) this;
		}

		public Criteria andFull_nameLessThanOrEqualTo(String value) {
			addCriterion("full_name <=", value, "full_name");
			return (Criteria) this;
		}

		public Criteria andFull_nameLike(String value) {
			addCriterion("full_name like", value, "full_name");
			return (Criteria) this;
		}

		public Criteria andFull_nameNotLike(String value) {
			addCriterion("full_name not like", value, "full_name");
			return (Criteria) this;
		}

		public Criteria andFull_nameIn(List<String> values) {
			addCriterion("full_name in", values, "full_name");
			return (Criteria) this;
		}

		public Criteria andFull_nameNotIn(List<String> values) {
			addCriterion("full_name not in", values, "full_name");
			return (Criteria) this;
		}

		public Criteria andFull_nameBetween(String value1, String value2) {
			addCriterion("full_name between", value1, value2, "full_name");
			return (Criteria) this;
		}

		public Criteria andFull_nameNotBetween(String value1, String value2) {
			addCriterion("full_name not between", value1, value2, "full_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUser_nameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUser_nameEqualTo(String value) {
			addCriterion("user_name =", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameGreaterThan(String value) {
			addCriterion("user_name >", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameLessThan(String value) {
			addCriterion("user_name <", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameLike(String value) {
			addCriterion("user_name like", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameNotLike(String value) {
			addCriterion("user_name not like", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameIn(List<String> values) {
			addCriterion("user_name in", values, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_passwordIsNull() {
			addCriterion("user_password is null");
			return (Criteria) this;
		}

		public Criteria andUser_passwordIsNotNull() {
			addCriterion("user_password is not null");
			return (Criteria) this;
		}

		public Criteria andUser_passwordEqualTo(String value) {
			addCriterion("user_password =", value, "user_password");
			return (Criteria) this;
		}

		public Criteria andUser_passwordNotEqualTo(String value) {
			addCriterion("user_password <>", value, "user_password");
			return (Criteria) this;
		}

		public Criteria andUser_passwordGreaterThan(String value) {
			addCriterion("user_password >", value, "user_password");
			return (Criteria) this;
		}

		public Criteria andUser_passwordGreaterThanOrEqualTo(String value) {
			addCriterion("user_password >=", value, "user_password");
			return (Criteria) this;
		}

		public Criteria andUser_passwordLessThan(String value) {
			addCriterion("user_password <", value, "user_password");
			return (Criteria) this;
		}

		public Criteria andUser_passwordLessThanOrEqualTo(String value) {
			addCriterion("user_password <=", value, "user_password");
			return (Criteria) this;
		}

		public Criteria andUser_passwordLike(String value) {
			addCriterion("user_password like", value, "user_password");
			return (Criteria) this;
		}

		public Criteria andUser_passwordNotLike(String value) {
			addCriterion("user_password not like", value, "user_password");
			return (Criteria) this;
		}

		public Criteria andUser_passwordIn(List<String> values) {
			addCriterion("user_password in", values, "user_password");
			return (Criteria) this;
		}

		public Criteria andUser_passwordNotIn(List<String> values) {
			addCriterion("user_password not in", values, "user_password");
			return (Criteria) this;
		}

		public Criteria andUser_passwordBetween(String value1, String value2) {
			addCriterion("user_password between", value1, value2, "user_password");
			return (Criteria) this;
		}

		public Criteria andUser_passwordNotBetween(String value1, String value2) {
			addCriterion("user_password not between", value1, value2, "user_password");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andRoleIsNull() {
			addCriterion("role is null");
			return (Criteria) this;
		}

		public Criteria andRoleIsNotNull() {
			addCriterion("role is not null");
			return (Criteria) this;
		}

		public Criteria andRoleEqualTo(String value) {
			addCriterion("role =", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotEqualTo(String value) {
			addCriterion("role <>", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleGreaterThan(String value) {
			addCriterion("role >", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleGreaterThanOrEqualTo(String value) {
			addCriterion("role >=", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLessThan(String value) {
			addCriterion("role <", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLessThanOrEqualTo(String value) {
			addCriterion("role <=", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLike(String value) {
			addCriterion("role like", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotLike(String value) {
			addCriterion("role not like", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleIn(List<String> values) {
			addCriterion("role in", values, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotIn(List<String> values) {
			addCriterion("role not in", values, "role");
			return (Criteria) this;
		}

		public Criteria andRoleBetween(String value1, String value2) {
			addCriterion("role between", value1, value2, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotBetween(String value1, String value2) {
			addCriterion("role not between", value1, value2, "role");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user
	 * @mbg.generated  Sat Mar 25 20:50:26 ICT 2023
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 25 20:50:26 ICT 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}